[package]
name = "bandit-rs"
version = "0.1.0"
authors = ["hardkey <adam.shimi@toulouse-inp.fr>"]
edition = "2018"

[dependencies]
rand = "0.7.2"
rand_distr = "0.2.2"
dyn-clone = "1.0.1"
gnuplot = "0.0.33"
